version: "3.2"
services:
  nginx:
    restart: "no"
    build: .
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    links:
      - api:api
  api:
    restart: "no"
    build: ../tnki-api/
    ports:
      - "3010:3000"
    volumes:
     - /etc/letsencrypt:/etc/letsencrypt
     - ~/.m2:/root/.m2
     - ../tnki-api:/src/tnki-api
    command: >
      bash -c "cd /src/tnki-api
      && lein npm install
      && lein trampoline run -m clojure.main scripts/build.clj
      && ./tnki-server"
  
